import { createCustomIcon } from '~/adapters/antd';
import _RemoveIcon from '~/assets/images/icon-remove.svg';
import _EmailIcon from '~/assets/images/icon-email.svg';
import _NotificationIcon from '~/assets/images/icon-notification.svg';
import _DisputeIcon from '~/assets/images/icon-dispute.svg';
import _CheckIcon from '~/assets/images/icon-check.svg';
import _SettingsIcon from '~/assets/images/icon-settings.svg';
import _InfoIcon from '~/assets/images/icon-info.svg';
import _AddIcon from '~/assets/images/icon-add.svg';
import _CalendarIcon from '~/assets/images/icon-calendar.svg';
import _HourGlassIcon from '~/assets/images/icon-hour-glass.svg';

export const RemoveIcon = createCustomIcon(_RemoveIcon);
export const EmailIcon = createCustomIcon(_EmailIcon);
export const NotificationIcon = createCustomIcon(_NotificationIcon);
export const DisputeIcon = createCustomIcon(_DisputeIcon);
export const CheckIcon = createCustomIcon(_CheckIcon);
export const SettingsIcon = createCustomIcon(_SettingsIcon);
export const InfoIcon = createCustomIcon(_InfoIcon);
export const AddIcon = createCustomIcon(_AddIcon);
export const CalendarIcon = createCustomIcon(_CalendarIcon);
export const HourGlassIcon = createCustomIcon(_HourGlassIcon);
